### ISSUE TITLE
About automating game installation.

### ISSUE THREAD

**Issue by brainiac19** [Phalcode/crackpipe-app#134] opened 2023-07-09 17:37 UTC
**Is your feature request related to a problem? Please describe.**
I'm not frustrated.

**Describe the solution you'd like**
I understand it's nearly impossible to automate it by just the crackpipe app, as there are god knows how many ways an installation can be  implemented. But it seems possible to leave the work to the backend admins.

First of all, we gotta admit there will be some setups that will be too painful to automate. So maybe combine two methods to make things easier on the client side, installation guides & automation.

I'm here about the automation. I'm just gonna call the first method formatted automation from here, which uses a yaml or json file to list the steps to install the game, then the client app perform all the steps to install them. Any related problem might need to be fixed by the devs, and that's some workload. It's functionality will still be limited, which does make it safer though. The setup.exe might require some manual intervention which could ideally be automated by scripts, on different OS there might be different stuff that needs to be done, for different games different forms of patches might need to be installed. Considering how little things can be actually done by it, I doubt how necessary it will be, eventually. Like maybe just go with the installation guides.

The second method I have in mind is scripted automation. It can do more, could actually make installations unattended, but not as safe. I'm thinking python with pywinauto. But of course, think about how you need to prepare python binaries for different OS, different venv for each installation script, that's also a headache. 

I'm inclined to the scripting method, as I really think it would make things neat for end users. Maybe we'll have people hosting crackpipe-automated game installation server, even sonarr, prowlarr for crackpipe in the future. But technically the automation might just be equally hard to implement. So I'm just gonna drop my thoughts here.

**Describe alternatives you've considered**
Show a page that says `Go google it if you can't figure it out.`

**Additional context**

**Comment by Alfagun74** [comment] 2023-07-09 17:51
Closed as a duplicate of #18, thanks for the input tho, we will think about it!

**Closed by Alfagun74** 2023-07-09 17:51 UTC
Labels: enhancement
